name: srikanth-cvat
on:
  workflow_dispatch

jobs:
  Unit_testing:
      if: |
        github.event.pull_request.draft == false &&
        !startsWith(github.event.pull_request.title, '[WIP]') &&
        !startsWith(github.event.pull_request.title, '[Dependent]')
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Getting SHA from the default branch
        id: get-sha
        run: |
          URL_get_default_branch="https://api.github.com/repos/${{ github.repository }}"
          DEFAULT_BRANCH=$(curl -s -X GET -G ${URL_get_default_branch} | jq -r '.default_branch')
          URL_get_sha_default_branch="https://api.github.com/repos/${{ github.repository }}/git/ref/heads/${DEFAULT_BRANCH}"
          SHA=$(curl -s -X GET -G ${URL_get_sha_default_branch}  | jq .object.sha | tr -d '"')
          echo ::set-output name=default_branch::${DEFAULT_BRANCH}
          echo ::set-output name=sha::${SHA}
      - name: Waiting a cache creation in the default branch
        run: |
          URL_runs="https://api.github.com/repos/${{ github.repository }}/actions/workflows/cache.yml/runs"
          SLEEP=45
          NUMBER_ATTEMPTS=10
          while [[ ${NUMBER_ATTEMPTS} -gt 0 ]]; do
            RUN_status=$(curl -s -X GET -G ${URL_runs} | jq -r '.workflow_runs[]? | select((.head_sha == "${{ steps.get-sha.outputs.sha }}") and (.event == "push") and (.name == "Cache") and (.head_branch == "${{ steps.get-sha.outputs.default_branch }}")) | .status')
            if [[ ${RUN_status} == "completed" ]]; then
              echo "The cache creation on the '${{ steps.get-sha.outputs.default_branch }}' branch has finished. Status: ${RUN_status}"
              break
            else
              echo "The creation of the cache is not yet complete."
              echo "There are still attempts to check the cache: ${NUMBER_ATTEMPTS}"
              echo "Status of caching in the '${{ steps.get-sha.outputs.default_branch }}' branch: ${RUN_status}"
              echo "sleep ${SLEEP}"
              sleep ${SLEEP}
              ((NUMBER_ATTEMPTS--))
            fi
          done
          if [[ ${NUMBER_ATTEMPTS} -eq 0 ]]; then
            echo "Number of attempts expired!"
            echo "Probably the creation of the cache is not yet complete. Will continue working without the cache."
          fi
